name: Pull request master

on:
  pull_request:
    branches:
      - master

jobs:
  inspirehep-pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  inspirehep-tests:
    needs: [inspirehep-pre-commit]
    uses: ./.github/workflows/inspirehep-tests.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
